<?php

namespace Database\Seeders;

use App\Models\Bidang;
use App\Models\Data;
use App\Models\DataValue;
use App\Models\Frekuensi;
use App\Models\Katakunci;
use App\Models\Tema;
use App\Models\Urusan;
use App\Models\User;
use Illuminate\Database\Seeder;

class DataSeeder extends Seeder
{
    public function run(): void
    {
        $temaIds = Tema::pluck('id_tema')->all();
        $urusanIds = Urusan::pluck('id_urusan')->all();
        $bidangIds = Bidang::pluck('id_bidang')->all();
        $frekuensiMap = Frekuensi::pluck('id_frekuensi', 'nama_frekuensi')->all();
        $userMap = User::pluck('id', 'email')->all();
        $inputerIds = User::where('role_id', 2)->orderBy('id')->pluck('id')->values()->all();

        $defaultTema = $temaIds[0] ?? 1;
        $defaultUrusan = $urusanIds[0] ?? 1;
        $defaultBidang = $bidangIds[0] ?? 1;
        $defaultFrekuensi = $frekuensiMap['Tahunan'] ?? 1;
        $fallbackUserId = User::value('id') ?? 1;

        $datasets = [
            [
                'nama_data' => 'Indeks Pembangunan Manusia',
                'deskripsi' => 'Indeks komposit yang menggambarkan capaian pembangunan manusia daerah.',
                'id_tema' => 3,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Indeks',
                'sumber' => 'BPS Kabupaten',
                'kata_kunci' => 'ipm pembangunan manusia kualitas hidup',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi indikator makro utama dalam pemantauan target RPJMD.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2021' => 73.42, '2022' => 74.12, '2023' => 74.86, '2024' => 75.39],
            ],
            [
                'nama_data' => 'Rata-rata Lama Sekolah',
                'deskripsi' => 'Rata-rata jumlah tahun sekolah yang ditempuh penduduk usia 25 tahun ke atas.',
                'id_tema' => 2,
                'id_urusan' => 1,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Tahun',
                'sumber' => 'Dinas Pendidikan',
                'kata_kunci' => 'pendidikan sekolah ipm rls',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan sebagai komponen pendidikan dalam perhitungan IPM.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2021' => 8.61, '2022' => 8.76, '2023' => 8.91, '2024' => 9.05],
            ],
            [
                'nama_data' => 'Harapan Lama Sekolah',
                'deskripsi' => 'Perkiraan lamanya sekolah yang akan ditempuh anak usia sekolah pada masa mendatang.',
                'id_tema' => 2,
                'id_urusan' => 1,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Tahun',
                'sumber' => 'Dinas Pendidikan',
                'kata_kunci' => 'pendidikan sekolah anak hls',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi indikator akses pendidikan jangka panjang.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2021' => 13.01, '2022' => 13.24, '2023' => 13.41, '2024' => 13.57],
            ],
            [
                'nama_data' => 'Angka Partisipasi Murni SD',
                'deskripsi' => 'Persentase penduduk usia SD yang bersekolah tepat pada jenjang sekolah dasar.',
                'id_tema' => 4,
                'id_urusan' => 1,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Pendidikan',
                'kata_kunci' => 'apm sd pendidikan dasar',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk memantau pemerataan akses pendidikan dasar.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2021' => 96.24, '2022' => 96.81, '2023' => 97.18, '2024' => 97.52],
            ],
            [
                'nama_data' => 'Angka Partisipasi Murni SMP',
                'deskripsi' => 'Persentase penduduk usia SMP yang bersekolah tepat pada jenjang sekolah menengah pertama.',
                'id_tema' => 4,
                'id_urusan' => 1,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Pendidikan',
                'kata_kunci' => 'apm smp pendidikan menengah',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mencerminkan keberlanjutan akses pendidikan setelah tamat SD.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2021' => 84.37, '2022' => 85.62, '2023' => 86.54, '2024' => 87.43],
            ],
            [
                'nama_data' => 'Persentase Guru Bersertifikat',
                'deskripsi' => 'Persentase guru pada satuan pendidikan dasar dan menengah yang telah memiliki sertifikat pendidik.',
                'id_tema' => 8,
                'id_urusan' => 1,
                'id_bidang' => 1,
                'frekuensi' => 'Semesteran',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Pendidikan',
                'kata_kunci' => 'guru sertifikasi mutu pendidikan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Dipantau per semester untuk evaluasi mutu tenaga pendidik.',
                'uploader_email' => 'sari.dewi@bappeda.test',
                'values' => ['2023-S1' => 72.4, '2023-S2' => 73.8, '2024-S1' => 75.1, '2024-S2' => 76.5],
            ],
            [
                'nama_data' => 'Angka Harapan Hidup',
                'deskripsi' => 'Perkiraan rata-rata lamanya hidup penduduk sejak lahir.',
                'id_tema' => 2,
                'id_urusan' => 2,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Tahun',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'kesehatan umur harapan hidup',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi salah satu komponen pembentuk indeks pembangunan manusia.',
                'uploader_email' => 'nyoman.wiratmaja@bappeda.test',
                'values' => ['2021' => 71.52, '2022' => 71.84, '2023' => 72.16, '2024' => 72.41],
            ],
            [
                'nama_data' => 'Prevalensi Stunting Balita',
                'deskripsi' => 'Persentase balita yang mengalami stunting berdasarkan hasil pengukuran status gizi.',
                'id_tema' => 5,
                'id_urusan' => 2,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'stunting balita gizi kesehatan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Masuk indikator prioritas penurunan stunting daerah.',
                'uploader_email' => 'desak.paramita@bappeda.test',
                'values' => ['2021' => 21.46, '2022' => 19.84, '2023' => 18.21, '2024' => 16.95],
            ],
            [
                'nama_data' => 'Cakupan Imunisasi Dasar Lengkap',
                'deskripsi' => 'Persentase bayi yang mendapatkan imunisasi dasar lengkap sesuai jadwal pelayanan.',
                'id_tema' => 7,
                'id_urusan' => 2,
                'id_bidang' => 3,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'imunisasi bayi kesehatan idl',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Disajikan bulanan untuk monitoring kinerja layanan imunisasi.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2024-01' => 88.2, '2024-02' => 89.1, '2024-03' => 90.4, '2024-04' => 91.3],
            ],
            [
                'nama_data' => 'Persalinan di Fasilitas Kesehatan',
                'deskripsi' => 'Persentase persalinan yang ditangani di fasilitas pelayanan kesehatan.',
                'id_tema' => 8,
                'id_urusan' => 2,
                'id_bidang' => 1,
                'frekuensi' => 'Triwulanan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'persalinan faskes ibu kesehatan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk mengevaluasi keselamatan persalinan ibu dan bayi.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2024-TW1' => 93.5, '2024-TW2' => 94.1, '2024-TW3' => 94.6, '2024-TW4' => 95.2],
            ],
            [
                'nama_data' => 'Jumlah Kematian Ibu',
                'deskripsi' => 'Jumlah kasus kematian ibu pada masa kehamilan, persalinan, dan nifas dalam satu tahun.',
                'id_tema' => 7,
                'id_urusan' => 2,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Kasus',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'kematian ibu kesehatan maternal',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi indikator prioritas dalam evaluasi layanan kesehatan ibu.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2021' => 8, '2022' => 7, '2023' => 6, '2024' => 5],
            ],
            [
                'nama_data' => 'Cakupan Kepesertaan Jaminan Kesehatan Nasional',
                'deskripsi' => 'Persentase penduduk yang terdaftar aktif dalam program Jaminan Kesehatan Nasional.',
                'id_tema' => 3,
                'id_urusan' => 2,
                'id_bidang' => 3,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Kesehatan',
                'kata_kunci' => 'jkn bpjs kesehatan kepesertaan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Monitoring bulanan untuk perluasan perlindungan kesehatan masyarakat.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2024-01' => 93.2, '2024-02' => 93.6, '2024-03' => 94.0, '2024-04' => 94.3],
            ],
            [
                'nama_data' => 'Persentase Penduduk Miskin',
                'deskripsi' => 'Persentase penduduk yang berada di bawah garis kemiskinan daerah.',
                'id_tema' => 3,
                'id_urusan' => 7,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'BPS Kabupaten',
                'kata_kunci' => 'kemiskinan sosial kesejahteraan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Dipakai untuk evaluasi efektivitas program penanggulangan kemiskinan.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2021' => 11.87, '2022' => 11.24, '2023' => 10.58, '2024' => 9.91],
            ],
            [
                'nama_data' => 'Jumlah KPM Penerima Bantuan Sosial Daerah',
                'deskripsi' => 'Jumlah keluarga penerima manfaat yang mendapatkan intervensi bantuan sosial dari pemerintah daerah.',
                'id_tema' => 4,
                'id_urusan' => 7,
                'id_bidang' => 3,
                'frekuensi' => 'Semesteran',
                'satuan' => 'Keluarga',
                'sumber' => 'Dinas Sosial',
                'kata_kunci' => 'bansos kpm sosial keluarga',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk memantau jangkauan intervensi sosial daerah.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2023-S1' => 12480, '2023-S2' => 12720, '2024-S1' => 12965, '2024-S2' => 13110],
            ],
            [
                'nama_data' => 'Tingkat Pengangguran Terbuka',
                'deskripsi' => 'Persentase angkatan kerja yang belum memperoleh pekerjaan.',
                'id_tema' => 3,
                'id_urusan' => 8,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Tenaga Kerja',
                'kata_kunci' => 'tenaga kerja pengangguran ekonomi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi indikator utama kondisi pasar kerja daerah.',
                'uploader_email' => 'nyoman.wiratmaja@bappeda.test',
                'values' => ['2021' => 5.94, '2022' => 5.47, '2023' => 5.11, '2024' => 4.88],
            ],
            [
                'nama_data' => 'Jumlah Penempatan Tenaga Kerja',
                'deskripsi' => 'Jumlah pencari kerja yang berhasil ditempatkan melalui fasilitasi pemerintah daerah dan mitra.',
                'id_tema' => 4,
                'id_urusan' => 8,
                'id_bidang' => 3,
                'frekuensi' => 'Triwulanan',
                'satuan' => 'Orang',
                'sumber' => 'Dinas Tenaga Kerja',
                'kata_kunci' => 'penempatan tenaga kerja pencari kerja',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Disajikan per triwulan untuk evaluasi penyerapan tenaga kerja.',
                'uploader_email' => 'desak.paramita@bappeda.test',
                'values' => ['2024-TW1' => 315, '2024-TW2' => 348, '2024-TW3' => 372, '2024-TW4' => 401],
            ],
            [
                'nama_data' => 'Persentase Penduduk Bekerja di Sektor Formal',
                'deskripsi' => 'Persentase penduduk bekerja yang terserap pada sektor formal.',
                'id_tema' => 8,
                'id_urusan' => 8,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Tenaga Kerja',
                'kata_kunci' => 'tenaga kerja formal pekerjaan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menggambarkan kualitas dan formalitas penyerapan pasar kerja.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2021' => 40.15, '2022' => 41.82, '2023' => 43.19, '2024' => 44.77],
            ],
            [
                'nama_data' => 'Indeks Pemberdayaan Gender',
                'deskripsi' => 'Indeks yang menggambarkan peran aktif perempuan dalam ekonomi, politik, dan pengambilan keputusan.',
                'id_tema' => 2,
                'id_urusan' => 9,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Indeks',
                'sumber' => 'Dinas P3A',
                'kata_kunci' => 'gender perempuan pemberdayaan ipg',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk evaluasi pengarusutamaan gender lintas perangkat daerah.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2021' => 70.84, '2022' => 72.14, '2023' => 73.28, '2024' => 74.03],
            ],
            [
                'nama_data' => 'Kasus Kekerasan Terhadap Perempuan dan Anak Tertangani',
                'deskripsi' => 'Persentase kasus kekerasan terhadap perempuan dan anak yang memperoleh penanganan layanan.',
                'id_tema' => 7,
                'id_urusan' => 9,
                'id_bidang' => 3,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas P3A',
                'kata_kunci' => 'kekerasan perempuan anak penanganan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Monitoring bulanan untuk respon cepat perlindungan perempuan dan anak.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2024-01' => 94.0, '2024-02' => 95.2, '2024-03' => 96.1, '2024-04' => 96.8],
            ],
            [
                'nama_data' => 'Persentase Desa Ramah Perempuan dan Peduli Anak',
                'deskripsi' => 'Persentase desa yang telah memenuhi indikator desa ramah perempuan dan peduli anak.',
                'id_tema' => 5,
                'id_urusan' => 9,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas P3A',
                'kata_kunci' => 'desa perempuan anak perlindungan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Bagian dari penguatan pembangunan inklusif di wilayah desa.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2021' => 28.6, '2022' => 34.9, '2023' => 40.3, '2024' => 46.8],
            ],
            [
                'nama_data' => 'Produksi Padi',
                'deskripsi' => 'Jumlah produksi padi gabah kering giling dalam satu tahun.',
                'id_tema' => 6,
                'id_urusan' => 10,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Ton',
                'sumber' => 'Dinas Pertanian',
                'kata_kunci' => 'pertanian padi pangan produksi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Dipakai untuk analisis ketahanan pangan wilayah kabupaten.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2021' => 53160, '2022' => 53820, '2023' => 55140, '2024' => 54760],
            ],
            [
                'nama_data' => 'Produksi Jagung',
                'deskripsi' => 'Jumlah produksi jagung pipilan kering dalam satu tahun.',
                'id_tema' => 6,
                'id_urusan' => 10,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Ton',
                'sumber' => 'Dinas Pertanian',
                'kata_kunci' => 'pertanian jagung pangan produksi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi komoditas utama pendukung diversifikasi pangan daerah.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2021' => 18120, '2022' => 18740, '2023' => 19480, '2024' => 20120],
            ],
            [
                'nama_data' => 'Ketersediaan Cadangan Pangan Pemerintah Daerah',
                'deskripsi' => 'Jumlah cadangan pangan pemerintah daerah yang tersedia untuk antisipasi gejolak dan darurat.',
                'id_tema' => 7,
                'id_urusan' => 10,
                'id_bidang' => 2,
                'frekuensi' => 'Semesteran',
                'satuan' => 'Ton',
                'sumber' => 'Dinas Ketahanan Pangan',
                'kata_kunci' => 'cadangan pangan beras pemerintah daerah',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Dipantau semesteran untuk kesiapsiagaan pangan dan bencana.',
                'uploader_email' => 'sari.dewi@bappeda.test',
                'values' => ['2023-S1' => 112.5, '2023-S2' => 118.0, '2024-S1' => 124.5, '2024-S2' => 129.0],
            ],
            [
                'nama_data' => 'Skor Pola Pangan Harapan',
                'deskripsi' => 'Skor komposisi konsumsi pangan masyarakat dibandingkan dengan pola konsumsi ideal.',
                'id_tema' => 2,
                'id_urusan' => 10,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Skor',
                'sumber' => 'Dinas Ketahanan Pangan',
                'kata_kunci' => 'pph konsumsi pangan gizi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mencerminkan kualitas konsumsi pangan rumah tangga secara agregat.',
                'uploader_email' => 'nyoman.wiratmaja@bappeda.test',
                'values' => ['2021' => 88.4, '2022' => 89.2, '2023' => 90.7, '2024' => 91.5],
            ],
            [
                'nama_data' => 'Cakupan Layanan Air Minum Layak',
                'deskripsi' => 'Persentase rumah tangga yang memiliki akses terhadap air minum layak.',
                'id_tema' => 3,
                'id_urusan' => 3,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas PUPR',
                'kata_kunci' => 'air minum sanitasi infrastruktur',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menunjukkan peningkatan layanan dasar pada infrastruktur permukiman.',
                'uploader_email' => 'desak.paramita@bappeda.test',
                'values' => ['2021' => 81.92, '2022' => 83.55, '2023' => 85.18, '2024' => 86.72],
            ],
            [
                'nama_data' => 'Cakupan Sanitasi Layak',
                'deskripsi' => 'Persentase rumah tangga yang memiliki akses terhadap sanitasi layak.',
                'id_tema' => 3,
                'id_urusan' => 3,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas PUPR',
                'kata_kunci' => 'sanitasi kesehatan lingkungan permukiman',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk mengevaluasi kualitas sanitasi dan kesehatan lingkungan.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2021' => 77.11, '2022' => 78.64, '2023' => 80.03, '2024' => 81.44],
            ],
            [
                'nama_data' => 'Panjang Jalan Kabupaten Kondisi Baik',
                'deskripsi' => 'Total panjang jalan kabupaten yang berada dalam kondisi baik dan mantap.',
                'id_tema' => 5,
                'id_urusan' => 3,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Kilometer',
                'sumber' => 'Dinas PUPR',
                'kata_kunci' => 'jalan infrastruktur konektivitas mantap',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mendukung analisis konektivitas antarwilayah dan pusat pertumbuhan.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2021' => 401.8, '2022' => 412.5, '2023' => 428.7, '2024' => 441.2],
            ],
            [
                'nama_data' => 'Panjang Saluran Irigasi Fungsional',
                'deskripsi' => 'Panjang saluran irigasi yang berfungsi baik untuk mendukung areal pertanian produktif.',
                'id_tema' => 6,
                'id_urusan' => 3,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Kilometer',
                'sumber' => 'Dinas PUPR',
                'kata_kunci' => 'irigasi pertanian air saluran',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Berperan penting dalam keberlanjutan produksi pertanian pangan.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2021' => 286.4, '2022' => 291.7, '2023' => 298.5, '2024' => 304.1],
            ],
            [
                'nama_data' => 'Persentase Drainase Perkotaan Kondisi Baik',
                'deskripsi' => 'Persentase jaringan drainase perkotaan yang berada dalam kondisi baik dan berfungsi.',
                'id_tema' => 8,
                'id_urusan' => 3,
                'id_bidang' => 2,
                'frekuensi' => 'Triwulanan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas PUPR',
                'kata_kunci' => 'drainase kota infrastruktur banjir',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Dipantau triwulanan untuk melihat kesiapan infrastruktur musim hujan.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2024-TW1' => 68.3, '2024-TW2' => 69.5, '2024-TW3' => 70.7, '2024-TW4' => 72.1],
            ],
            [
                'nama_data' => 'Persentase Rumah Layak Huni',
                'deskripsi' => 'Persentase rumah tangga yang menempati rumah sesuai standar kelayakan.',
                'id_tema' => 3,
                'id_urusan' => 4,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Perumahan',
                'kata_kunci' => 'perumahan rumah layak huni permukiman',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mencerminkan kualitas kondisi hunian rumah tangga di daerah.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2021' => 80.12, '2022' => 81.33, '2023' => 82.74, '2024' => 84.06],
            ],
            [
                'nama_data' => 'Jumlah Rumah Tangga Penerima Bantuan RTLH',
                'deskripsi' => 'Jumlah rumah tangga yang menerima bantuan peningkatan kualitas rumah tidak layak huni.',
                'id_tema' => 5,
                'id_urusan' => 4,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Rumah Tangga',
                'sumber' => 'Dinas Perumahan',
                'kata_kunci' => 'rtlh bantuan rumah perumahan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Program prioritas peningkatan kualitas hunian masyarakat berpenghasilan rendah.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2021' => 318, '2022' => 346, '2023' => 372, '2024' => 395],
            ],
            [
                'nama_data' => 'Persentase Kawasan Kumuh Tertangani',
                'deskripsi' => 'Persentase luas kawasan kumuh yang telah ditangani melalui intervensi infrastruktur dan pemberdayaan.',
                'id_tema' => 7,
                'id_urusan' => 4,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas Perumahan',
                'kata_kunci' => 'kumuh permukiman penanganan kawasan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mendukung target penurunan luas kawasan permukiman kumuh perkotaan.',
                'uploader_email' => 'sari.dewi@bappeda.test',
                'values' => ['2021' => 54.2, '2022' => 60.8, '2023' => 67.5, '2024' => 73.1],
            ],
            [
                'nama_data' => 'Jumlah Gangguan Ketentraman dan Ketertiban Umum',
                'deskripsi' => 'Jumlah kejadian gangguan ketentraman dan ketertiban umum yang tercatat oleh perangkat daerah.',
                'id_tema' => 7,
                'id_urusan' => 5,
                'id_bidang' => 3,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Kejadian',
                'sumber' => 'Satpol PP',
                'kata_kunci' => 'trantibum gangguan satpolpp ketertiban',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Data operasional untuk pemantauan kondisi ketertiban umum daerah.',
                'uploader_email' => 'nyoman.wiratmaja@bappeda.test',
                'values' => ['2024-01' => 21, '2024-02' => 18, '2024-03' => 20, '2024-04' => 17],
            ],
            [
                'nama_data' => 'Waktu Respon Penanganan Gangguan Trantibum',
                'deskripsi' => 'Rata-rata waktu respon petugas dalam menangani laporan gangguan ketentraman dan ketertiban umum.',
                'id_tema' => 8,
                'id_urusan' => 5,
                'id_bidang' => 1,
                'frekuensi' => 'Mingguan',
                'satuan' => 'Menit',
                'sumber' => 'Satpol PP',
                'kata_kunci' => 'respon trantibum layanan pengaduan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Disajikan mingguan untuk evaluasi kecepatan layanan penanganan lapangan.',
                'uploader_email' => 'desak.paramita@bappeda.test',
                'values' => ['2024-W01' => 42, '2024-W02' => 39, '2024-W03' => 37, '2024-W04' => 35],
            ],
            [
                'nama_data' => 'Jumlah Satlinmas Aktif',
                'deskripsi' => 'Jumlah anggota satuan perlindungan masyarakat yang aktif dan terdata.',
                'id_tema' => 4,
                'id_urusan' => 6,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Orang',
                'sumber' => 'BPBD dan Kesbangpol',
                'kata_kunci' => 'satlinmas linmas perlindungan masyarakat',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi kekuatan pendukung ketenteraman dan kesiapsiagaan masyarakat.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2021' => 1325, '2022' => 1388, '2023' => 1442, '2024' => 1495],
            ],
            [
                'nama_data' => 'Persentase Desa Tangguh Bencana Aktif',
                'deskripsi' => 'Persentase desa yang aktif menjalankan program desa tangguh bencana.',
                'id_tema' => 5,
                'id_urusan' => 6,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'BPBD',
                'kata_kunci' => 'destana bencana desa kesiapsiagaan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mendukung penguatan ketahanan masyarakat terhadap risiko bencana.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2021' => 24.5, '2022' => 28.0, '2023' => 33.7, '2024' => 39.2],
            ],
            [
                'nama_data' => 'Cakupan Pelatihan Kebencanaan Aparatur Desa',
                'deskripsi' => 'Persentase aparatur desa yang telah mengikuti pelatihan penanggulangan bencana dasar.',
                'id_tema' => 8,
                'id_urusan' => 6,
                'id_bidang' => 1,
                'frekuensi' => 'Semesteran',
                'satuan' => 'Persen',
                'sumber' => 'BPBD',
                'kata_kunci' => 'pelatihan bencana aparatur desa',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Pemantauan semesteran untuk peningkatan kapasitas aparatur pemerintahan desa.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2023-S1' => 41.8, '2023-S2' => 45.6, '2024-S1' => 49.2, '2024-S2' => 53.4],
            ],
            [
                'nama_data' => 'Jumlah UMKM Aktif',
                'deskripsi' => 'Jumlah pelaku usaha mikro kecil menengah yang aktif menjalankan usaha di daerah.',
                'id_tema' => 5,
                'id_urusan' => 11,
                'id_bidang' => 3,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Unit',
                'sumber' => 'Dinas Koperasi dan UMKM',
                'kata_kunci' => 'umkm usaha ekonomi kerakyatan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi indikator perkembangan ekonomi lokal dan kewirausahaan masyarakat.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2021' => 11860, '2022' => 12480, '2023' => 13140, '2024' => 13895],
            ],
            [
                'nama_data' => 'Nilai Investasi PMDN',
                'deskripsi' => 'Nilai realisasi Penanaman Modal Dalam Negeri yang tercatat dalam periode pelaporan.',
                'id_tema' => 6,
                'id_urusan' => 11,
                'id_bidang' => 3,
                'frekuensi' => 'Triwulanan',
                'satuan' => 'Miliar Rupiah',
                'sumber' => 'DPMPTSP',
                'kata_kunci' => 'investasi pmdn penanaman modal ekonomi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk memantau iklim investasi dan daya tarik daerah.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2024-TW1' => 128.4, '2024-TW2' => 136.8, '2024-TW3' => 142.1, '2024-TW4' => 149.7],
            ],
            [
                'nama_data' => 'Kunjungan Wisatawan Nusantara',
                'deskripsi' => 'Jumlah kunjungan wisatawan nusantara ke destinasi wisata unggulan daerah.',
                'id_tema' => 5,
                'id_urusan' => 11,
                'id_bidang' => 3,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Kunjungan',
                'sumber' => 'Dinas Pariwisata',
                'kata_kunci' => 'wisatawan nusantara pariwisata kunjungan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Monitoring bulanan untuk melihat dinamika kunjungan wisata domestik.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2024-01' => 18420, '2024-02' => 19135, '2024-03' => 20580, '2024-04' => 21490],
            ],
            [
                'nama_data' => 'Rasio Elektrifikasi Rumah Tangga',
                'deskripsi' => 'Persentase rumah tangga yang telah menikmati akses listrik.',
                'id_tema' => 6,
                'id_urusan' => 11,
                'id_bidang' => 2,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Dinas ESDM',
                'kata_kunci' => 'listrik energi rumah tangga elektrifikasi',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mengukur pemerataan akses energi rumah tangga hingga tingkat desa.',
                'uploader_email' => 'sari.dewi@bappeda.test',
                'values' => ['2021' => 97.11, '2022' => 97.82, '2023' => 98.34, '2024' => 98.91],
            ],
            [
                'nama_data' => 'Persentase Layanan Publik yang Terdigitalisasi',
                'deskripsi' => 'Persentase layanan publik prioritas yang telah tersedia dalam bentuk digital atau semi digital.',
                'id_tema' => 5,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Diskominfo',
                'kata_kunci' => 'digitalisasi layanan publik spbe',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Mendukung agenda transformasi digital pemerintah daerah.',
                'uploader_email' => 'nyoman.wiratmaja@bappeda.test',
                'values' => ['2021' => 42.3, '2022' => 51.7, '2023' => 60.4, '2024' => 68.9],
            ],
            [
                'nama_data' => 'Indeks Reformasi Birokrasi Perangkat Daerah',
                'deskripsi' => 'Nilai agregat reformasi birokrasi pada perangkat daerah berdasarkan hasil evaluasi internal.',
                'id_tema' => 8,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Nilai',
                'sumber' => 'Bagian Organisasi',
                'kata_kunci' => 'rb reformasi birokrasi perangkat daerah',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi ukuran kemajuan tata kelola pemerintahan daerah.',
                'uploader_email' => 'desak.paramita@bappeda.test',
                'values' => ['2021' => 67.8, '2022' => 70.6, '2023' => 73.4, '2024' => 75.9],
            ],
            [
                'nama_data' => 'Persentase Realisasi Belanja Prioritas Daerah',
                'deskripsi' => 'Persentase realisasi belanja pada program prioritas daerah terhadap alokasi anggarannya.',
                'id_tema' => 7,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Triwulanan',
                'satuan' => 'Persen',
                'sumber' => 'BPKAD',
                'kata_kunci' => 'realisasi belanja anggaran prioritas',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Digunakan untuk pengendalian pelaksanaan program prioritas daerah.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2024-TW1' => 18.6, '2024-TW2' => 41.2, '2024-TW3' => 67.8, '2024-TW4' => 94.5],
            ],
            [
                'nama_data' => 'Persentase Capaian Program Unggulan Kepala Daerah',
                'deskripsi' => 'Persentase capaian target tahunan pada program unggulan kepala daerah.',
                'id_tema' => 5,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Persen',
                'sumber' => 'Bappeda',
                'kata_kunci' => 'program unggulan target capaian',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Ringkasan capaian lintas perangkat daerah pada program unggulan daerah.',
                'uploader_email' => 'ananta@bappeda.test',
                'values' => ['2021' => 72.5, '2022' => 78.4, '2023' => 83.6, '2024' => 88.1],
            ],
            [
                'nama_data' => 'Persentase Data Statistik Sektoral Terverifikasi',
                'deskripsi' => 'Persentase dataset statistik sektoral yang telah melalui proses verifikasi dan validasi.',
                'id_tema' => 1,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Semesteran',
                'satuan' => 'Persen',
                'sumber' => 'Bappeda dan Diskominfo',
                'kata_kunci' => 'statistik sektoral verifikasi metadata',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menguatkan tata kelola satu data dan kualitas metadata daerah.',
                'uploader_email' => 'ayu.pradnyani@bappeda.test',
                'values' => ['2023-S1' => 54.2, '2023-S2' => 61.4, '2024-S1' => 69.5, '2024-S2' => 76.3],
            ],
            [
                'nama_data' => 'Jumlah Desa dengan Profil Pembangunan Tahunan Lengkap',
                'deskripsi' => 'Jumlah desa yang telah menyusun dan menyerahkan profil pembangunan tahunan secara lengkap.',
                'id_tema' => 6,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Tahunan',
                'satuan' => 'Desa',
                'sumber' => 'Bappeda',
                'kata_kunci' => 'profil desa pembangunan kewilayahan data',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Menjadi basis data kewilayahan untuk perencanaan berbasis desa.',
                'uploader_email' => 'ardika.putra@bappeda.test',
                'values' => ['2021' => 78, '2022' => 86, '2023' => 94, '2024' => 103],
            ],
            [
                'nama_data' => 'Indeks Risiko Bencana Daerah',
                'deskripsi' => 'Indeks yang menggambarkan tingkat risiko bencana daerah berdasarkan ancaman, kerentanan, dan kapasitas.',
                'id_tema' => 6,
                'id_urusan' => 6,
                'id_bidang' => 2,
                'frekuensi' => 'Lainnya',
                'satuan' => 'Indeks',
                'sumber' => 'BPBD',
                'kata_kunci' => 'risiko bencana indeks kebencanaan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Pemutakhiran dilakukan sesuai siklus kajian risiko bencana daerah.',
                'uploader_email' => 'rina.maheswari@bappeda.test',
                'values' => ['2020' => 142.6, '2022' => 137.9, '2024' => 131.4],
            ],
            [
                'nama_data' => 'Persentase Aduan Masyarakat Terselesaikan',
                'deskripsi' => 'Persentase aduan masyarakat yang berhasil ditindaklanjuti dan diselesaikan dalam periode pelaporan.',
                'id_tema' => 8,
                'id_urusan' => 11,
                'id_bidang' => 1,
                'frekuensi' => 'Bulanan',
                'satuan' => 'Persen',
                'sumber' => 'Inspektorat dan Diskominfo',
                'kata_kunci' => 'aduan masyarakat penyelesaian layanan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Monitoring bulanan untuk menjaga kualitas respon atas aspirasi masyarakat.',
                'uploader_email' => 'gede.saputra@bappeda.test',
                'values' => ['2024-01' => 86.4, '2024-02' => 87.9, '2024-03' => 89.1, '2024-04' => 90.7],
            ],
            [
                'nama_data' => 'Jumlah Kejadian Bencana yang Ditangani',
                'deskripsi' => 'Jumlah kejadian bencana yang mendapatkan penanganan tanggap darurat oleh pemerintah daerah.',
                'id_tema' => 7,
                'id_urusan' => 6,
                'id_bidang' => 3,
                'frekuensi' => 'Harian',
                'satuan' => 'Kejadian',
                'sumber' => 'BPBD',
                'kata_kunci' => 'bencana tanggap darurat penanganan',
                'tahun_terbit' => 2024,
                'informasi_tambahan' => 'Contoh data operasional harian untuk kebutuhan simulasi dashboard kebencanaan.',
                'uploader_email' => 'bagus.pramana@bappeda.test',
                'values' => ['2024-06-01' => 1, '2024-06-02' => 0, '2024-06-03' => 2, '2024-06-04' => 1],
            ],
        ];

        foreach ($datasets as $index => $dataset) {
            $userId = $userMap[$dataset['uploader_email']]
                ?? $inputerIds[$index % max(count($inputerIds), 1)]
                ?? $fallbackUserId;
            $frekuensiId = $frekuensiMap[$dataset['frekuensi']] ?? $defaultFrekuensi;

            $data = Data::updateOrCreate(
                ['nama_data' => $dataset['nama_data']],
                [
                    'id_user' => $userId,
                    'id_tema' => in_array($dataset['id_tema'], $temaIds, true) ? $dataset['id_tema'] : $defaultTema,
                    'id_urusan' => in_array($dataset['id_urusan'], $urusanIds, true) ? $dataset['id_urusan'] : $defaultUrusan,
                    'id_bidang' => in_array($dataset['id_bidang'], $bidangIds, true) ? $dataset['id_bidang'] : $defaultBidang,
                    'id_frekuensi' => $frekuensiId,
                    'deskripsi' => $dataset['deskripsi'],
                    'satuan' => $dataset['satuan'],
                    'sumber' => $dataset['sumber'],
                    'tahun_terbit' => $dataset['tahun_terbit'],
                    'informasi_tambahan' => $dataset['informasi_tambahan'],
                ]
            );

            $keywordIds = collect(explode(' ', $dataset['kata_kunci']))
                ->filter()
                ->map(function (string $keyword) {
                    return Katakunci::firstOrCreate([
                        'nama_katakunci' => trim($keyword),
                    ])->id_katakunci;
                })
                ->values()
                ->all();

            $data->katakunci()->sync($keywordIds);

            foreach ($dataset['values'] as $tahun => $nilai) {
                DataValue::updateOrCreate(
                    [
                        'id_data' => $data->id_data,
                        'tahun' => (string) $tahun,
                    ],
                    ['nilai' => $nilai]
                );
            }
        }
    }
}
